### PR TITLE
Autoplay on station change

### PR DESCRIPTION
**Pull request by ilijaveselica**
Should disable stop button :)

### CODE REVIEW

**Comment by vladimyr** [comment]
First, thanks for PR but there are two things I have mixed feelings about:
1. Autoplay on load is nice feature but there should be a way to opt-out? Url param maybe? 🤔 
2. Automatically invoking `#play` on station change isn't always correct, what would happen if stream is stoped and user changes station afterwards?

**Comment by ilijaveselica** [comment]
@vladimyr 
1. Makes sense to to use url param for autoplay on load
2. I agree that it isn't always "correct" from developer standpoint but from user perspective maybe it will make more sense - if you press a stop button and then change radio station, would there ever be a reason why you wouldn't want it to autoplay that station? In other words, why would you change radio station if you don't want to listen to it?

**Comment by ilijaveselica** [comment]
Seems like I will have to opt-out autoplay on page load: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by vladimyr** [comment]
> I agree that it isn't always "correct" from developer standpoint but from user perspective maybe it will make more sense - if you press a stop button and then change radio station, would there ever be a reason why you wouldn't want it to autoplay that station? In other words, why would you change radio station if you don't want to listen to it?

That makes perfect sense if previous state is _playing_ one but there is this initial _paused/ready_ state where changing station should (not) immediately start playback? :thinking: 

Anyway, I'm happy with current state of PR so merging it in right now :+1: :1st_place_medal:

**Pull request merged**
